0x0F. Load balancer

diff --git a/0x0F-load_balancer/1-install_load_balancer b/0x0F-load_balancer/1-install_load_balancer
--- a/0x0F-load_balancer/1-install_load_balancer
+++ b/0x0F-load_balancer/1-install_load_balancer
@@ -1,32 +1,60 @@
 #!/usr/bin/env bash
-# Create a script to install and configure HAProxy on lb-01 server
-# Configure HAProxy to send traffic to web-01 and web-02 servers
-# Distribute requests using a roundrobin algorithm
-# Make sure that HAProxy can be managed via an init script
+# Script for deploying a load balancer
 
-# Install and configure HAproxy on my lb-01 server.
-sudo apt-get -y update
-apt-get -y install haproxy
+echo -e "Performing system updates and basic checks...\n"
 
-# edit config file
-server_config=\
+function check_and_install() {
+    command -v "$1" &> /dev/null
+
+    # Ignore shellcheck error SC2181
+    # (check if return value is non-zero)
+    if [ $? -ne 0 ]; then
+        echo -e "Installing: $1\n"
+        sudo apt-get update -y -qq && \
+            sudo apt-get install -y "$1" -qq
+        echo -e "\n"
+    else
+        echo -e "${1} is already installed.\n"
+    fi
+}
+
+check_and_install haproxy # Install haproxy
+
+echo -e "\nSetting up configurations...\n"
+
+# Backup default configuration file
+sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup
+
+# Define load balancer configuration
+lb_config=\
 "
-frontend  besthor_frontend
-        bind *:80
-        mode http
-        default_backend besthor_backend
-backend besthor_backend
-        balance roundrobin
-        server 176572-web-01 54.165.168.252:80 check
-        server 176572-web-02 34.237.91.136:80 check
+defaults
+    mode http
+    timeout client 15s
+    timeout connect 10s
+    timeout server 15s
+    timeout http-request 10s
+frontend algomerix-tech-frontend
+    bind *:8080
+    default_backend algomerix-tech-backend
+
+backend algomerix-tech-backend
+    balance roundrobin
+    server web_server_01 54.165.47.248:80 check port 80
+    server web_server_02 100.25.193.107:80 check port 80
 "
-echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
 
-# enable haproxy to be started by init script
-echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
+# Ignore shellcheck error SC2154 (unassigned variable)
+echo "$lb_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg
 
-# Testing the HAproxy configuration file
-sudo haproxy -c -f /etc/haproxy/haproxy.cfg
+# Enable haproxy to be started by init script
+echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy
 
-# Restart the Nginx service
-sudo service haproxy restart
+echo "Configuration set - Round-robin load balancing between web_server_01 & web_server_02"
+
+# Start or restart haproxy service based on its status
+if [ "$(pgrep -c haproxy)" -le 0 ]; then
+    sudo service haproxy start
+else
+    sudo service haproxy restart
+fi
